### ISSUE TITLE
Refactor to use gulp-wrap

### ISSUE THREAD

**Issue by ghost** [efacilitation/gulp-wrap-commonjs#6]
Instead of doing the wrapping with lodash.template ourself we should use [gulp-wrap](https://github.com/adamayres/gulp-wrap).

**Comment by qraynaud** [comment]
That would be sad. guld wrap is powerful but does not support sourcemaps and I don't think they ever will (it looks hard to do with lodash templates as a base). Wouldn't it be better to add support for sourcemaps?

**Comment by alexlawrence** [comment]
We won´t be switching to gulp-wrap anytime soon. If you want to have sourcemaps support, please provide a pull request. Thank you.

**Comment by alexlawrence** [comment]
Ah, I see you already provided a pull request @qraynaud . We will review it soon.
